### ISSUE TITLE
Stack traces in console 

### ISSUE THREAD

**Issue by akondasif** [hcguersoy/qpowhash#2]
Greetings,

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found instances of improper exception handling.

According to CWE, exceptions should not be thrown in catch clauses. See https://cwe.mitre.org/ and https://wiki.sei.cmu.edu/confluence/display/java/ERR01-J.+Do+not+allow+exceptions+to+expose+sensitive+information

Source: https://github.com/hcguersoy/qpowhash/blob/master/.mvn/wrapper/MavenWrapperDownloader.java

Fix: https://github.com/hcguersoy/qpowhash/pull/1 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by hcguersoy** [comment]
Hi Akond,

this was  a finding in a 3rd party library, in detail the maven wrapper, see [https://github.com/takari/maven-wrapper](https://github.com/takari/maven-wrapper).

Due to that, closing this.
